### ISSUE TITLE
incomplete defacing

### ISSUE THREAD

**Issue by pbeukema** [poldracklab/pydeface#18]
Hi, 
Loving this software. During a recent defacing batch, one of my subjects T2w (although T1w fine) image ended up with most of the face left intact. Attached is a screenshot. Any thoughts here? I can use other utilities but prefer pydeface.
Thanks!
Patrick
<img width="1058" alt="openneuro_incom" src="https://user-images.githubusercontent.com/9040930/36559679-b0cd793e-17dc-11e8-867c-44e633d2c215.png">

**Comment by chrisfilo** [comment]
Have you tried estimating the defacing from T1w and applying to T2w using `--applyto` flag introduced in https://github.com/poldracklab/pydeface/pull/15?

**Comment by pbeukema** [comment]
Worked like a charm - thanks! 
pb
