### ISSUE TITLE
docker image 

### ISSUE THREAD

**Issue by CarinaFo** [poldracklab/pydeface#38]
Hi,

I wanted to get the docker image to run pydeface, unfortunately it doesn't work with tag:latest.

Thank you,

Carina

**Comment by Shotgunosine** [comment]
Hi Carina,

I was just able to pull the image with `docker pull poldracklab/pydeface:latest` and ran the tests with `docker run -it poldracklab/pydeface:latest pytest /pydeface` and they seem to be passing. Can you provide a little bit more information about the error you're getting?

Thanks,

Dylan

**Comment by CarinaFo** [comment]
sorry it works now, I forgot to add poldracklab, sorry stupid mistake.
