### ISSUE TITLE
Improper defacing before reorient

### ISSUE THREAD

**Issue by pstetz** [poldracklab/pydeface#41]
Hello,

For some subjects we have, parts of the brain are cut off instead of the face (see below images). However, pydeface seems to work when the image is reoriented first

You should be able to reproduce this issue by doing
```
curl https://patrickstetz.com/pydeface/in.nii.gz --output in.nii.gz
singularity run --cleanenv -B ./:/tmp/0 docker://poldracklab/pydeface pydeface ./in.nii.gz
```

### Input Image
<img width="2302" alt="in" src="https://user-images.githubusercontent.com/16963003/128567830-b2e2715f-bd9c-49bd-bdd7-1df92368feba.png">

### After defacing
<img width="2298" alt="in_deface" src="https://user-images.githubusercontent.com/16963003/128567839-f325068d-00b8-4b50-a9de-8e575a6949ce.png">

### Defacing after reorienting first
<img width="2301" alt="reorient_deface" src="https://user-images.githubusercontent.com/16963003/128567847-d6d6979c-4f76-4c9e-951d-f336d4171c34.png">

Would be happy to help by submitting a PR for this!!

Best,
Patrick

**Comment by pstetz** [comment]
Looks like this is already reported in #9

**Comment by ofgulban** [comment]
@pstetz , thanks for opening this issue :+1: . You are welcome to submit a pull request.

**Comment by effigies** [comment]
#9 covers this. PRs still welcome.
