### ISSUE TITLE
Detail the list of FSL dependencies

### ISSUE THREAD

**Issue by mateuszpawlik** [poldracklab/pydeface#44]
I want to use pydeface in a bigger context of data acquisition. I've added FSL into my Dockerfile. The problem is that FSL takes ~2.5h to install and ~16GB of space. I've posted some of the issues in https://github.com/ReproNim/neurodocker/issues/450

I'm wandering if I could at least reduce the container size by specifying more precise FSL dependencies, for example, FLIRT.

Here is the list of top-level directories in FSL directory and their sizes:
```
root@6778f59b8716:/opt/fsl-6.0.5.1# du -sh *
4.0K    LICENCE
4.0K    README
4.4G    bin
8.0K    build
3.1M    build.log
152K    config
2.3G    data
188M    doc
5.0M    etc
339M    extras
6.3G    fslpython
4.7M    include
1.6G    lib
264K    python
324K    refdoc
257M    src
2.4M    tcl
```

**Comment by kaczmarj** [comment]
@mateuszpawlik - neurodocker has a `minify` function designed to minimize docker images for particular commands. please see https://www.repronim.org/neurodocker/user_guide/minify.html for an example.
