### ISSUE TITLE
How do I set the path?

### ISSUE THREAD

**Issue by velpegor** [poldracklab/pydeface#47]
![image](https://user-images.githubusercontent.com/83739271/180978747-372901b5-c7e6-4d59-873e-e43a20980fee.png)

![image](https://user-images.githubusercontent.com/83739271/180978797-1b0d287d-6a8c-402e-9784-9d0ccc2b2074.png)

I don't know how to set it up. help me

**Comment by ofgulban** [comment]
Hi @velpegor , are you planning to use pydeface from your command line? In that case you do not need to edit the `initial_checks` functions. Instead, for example. you can do:
```
pydeface /path/to/T1w.nii.gz --template /path/to/template.nii.gz --facemask /path/to/facemask.nii.gz
```
Maybe this pull request might also be helpful to explain how the optional parameters are used from the command line interface: https://github.com/poldracklab/pydeface/pull/15

If these were not helpful, please elaborate further on the issue that you are having and tell what you want to accomplish.

**Comment by ofgulban** [comment]
No response from OP, closing for now.
