### ISSUE TITLE
FSL dependency check requires the complete FSL installation

### ISSUE THREAD

**Issue by mateuszpawlik** [poldracklab/pydeface#54]
I'm working on a Docker image for one of our pipelines. Pydeface is one of the tools in the chain. It depends on FSL. The complete FSL installation is time consuming and the resulting image is large. Pydeface seems to use only FLIRT binary out of many FSL tools. I managed to compile FLIRT from sources in my Docker image. The FLIRT binary is only 1MB large + its dependencies.

Unfortunately, [pydeface is looking for the `fsl` binary and not `flirt`](https://github.com/poldracklab/pydeface/blob/69a17a6817634d78c12aea955f981d48890bac96/pydeface/utils.py#L83C4-L84C66) and I fail to execute it. Are there more dependencies than FLIRT from the FSL tools? Could the check be simply substituted with `flirt`?

According to the [documentation](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation#Starting_the_programs), `fsl` binary is just a menu:
> To bring up a simple GUI which is just a menu of the main individual FSL GUI tools, just type fsl.

The following lines allowed me to successfully install and execute pydeface with only `flirt` binary.
```Dockerfile
RUN pipx install pydeface
RUN sed -i "s/shutil.which('fsl')/shutil.which('flirt')/g" /root/.local/pipx/venvs/pydeface/lib/python3.11/site-packages/pydeface/utils.py
```

**Comment by effigies** [comment]
Agree, it makes sense to switch to calling `which('flirt')`

**Comment by ofgulban** [comment]
Merged the PR now, closing.
