### ISSUE TITLE
defacing raw  images cut off frontal brain tissue

### ISSUE THREAD

**Issue by rschmaelzle** [poldracklab/pydeface#6]
Hi, 
i started using pydeface, but it cut off parts of the brain. It worked fine when using MNI-normalized data, but I wanted to share unprocessed raw data. Are there any additional suggestions that the data should conform to (e.g. resetting the origin?).
Thank you

**Comment by effigies** [comment]
I'll put in a plug here for [quickshear](https://github.com/nipy/quickshear). You supply it a brainmask, so it's guaranteed not to cut out brain (assuming the mask is good), and you can also manually set a margin to tweak the distance from the mask.

**Comment by rschmaelzle** [comment]
that sounds exactly like what I've been missing. thanks.
